# This file was generated by GoReleaser. DO NOT EDIT.
cask "kompadre" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "e267aade67412d0caaebcefff9b110cb382a5c43c3d7c897f1ee7276c1ededf7"
      url "https://github.com/SamuAlfageme/kompadre/releases/download/v#{version}/kompadre_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/SamuAlfageme/kompadre/"
    end
    on_arm do
      sha256 "6b4294fb8b621b30f143c8720072fc85b06be04878875cd60e9e3937b5e1b024"
      url "https://github.com/SamuAlfageme/kompadre/releases/download/v#{version}/kompadre_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/SamuAlfageme/kompadre/"
    end
  end

  on_linux do
    on_intel do
      sha256 "ccb1c3e69a8b821b53c92662bce63140b5d143026405b80f3cf7ec89d8c83fde"
      url "https://github.com/SamuAlfageme/kompadre/releases/download/v#{version}/kompadre_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/SamuAlfageme/kompadre/"
    end
    on_arm do
      sha256 "bd8d2bb142f97cdf35a06e31d7bf48b9107f71bed197ab60fe490283434affbb"
      url "https://github.com/SamuAlfageme/kompadre/releases/download/v#{version}/kompadre_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/SamuAlfageme/kompadre/"
    end
  end

  name "kompadre"
  desc "Compare Kubernetes clusters using kubeconfig files"
  homepage "https://github.com/SamuAlfageme/kompadre"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kompadre"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kompadre"]
    end
  end

  # No zap stanza required

end
