# This file was generated by GoReleaser. DO NOT EDIT.
cask "kompadre" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "7649e3166db4604f677257c5f1f31486489a0f98ac443fc251686c74838fe5be"
      url "https://github.com/SamuAlfageme/kompadre/releases/download/v#{version}/kompadre_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/SamuAlfageme/kompadre/"
    end
    on_arm do
      sha256 "6e22bd9a58a32bc2e80bb68fd50a0030c3e29df92a04ec2e077ea0f0a33c2cbc"
      url "https://github.com/SamuAlfageme/kompadre/releases/download/v#{version}/kompadre_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/SamuAlfageme/kompadre/"
    end
  end

  on_linux do
    on_intel do
      sha256 "1063f8387f0bf181f9d13d4fefb45053bae10898b65da8b09f4c06bcc68cb678"
      url "https://github.com/SamuAlfageme/kompadre/releases/download/v#{version}/kompadre_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/SamuAlfageme/kompadre/"
    end
    on_arm do
      sha256 "96c57bc1b5fb837f8aefba65069fff2b235cd16a415ef77c7c2695136ce02471"
      url "https://github.com/SamuAlfageme/kompadre/releases/download/v#{version}/kompadre_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/SamuAlfageme/kompadre/"
    end
  end

  name "kompadre"
  desc "Compare Kubernetes clusters using kubeconfig files"
  homepage "https://github.com/SamuAlfageme/kompadre"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kompadre"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kompadre"]
    end
  end

  # No zap stanza required

end
