# This file was generated by GoReleaser. DO NOT EDIT.
cask "kompadre" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "b64609960832a72fd8d8693e14cde404618f205efb3c42816663255ac9eba192"
      url "https://github.com/SamuAlfageme/kompadre/releases/download/v#{version}/kompadre_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/SamuAlfageme/kompadre/"
    end
    on_arm do
      sha256 "1741c41250fa5965dc7a5e13912ea7347a53c0dab6781b02c0da1f41c6a8b12b"
      url "https://github.com/SamuAlfageme/kompadre/releases/download/v#{version}/kompadre_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/SamuAlfageme/kompadre/"
    end
  end

  on_linux do
    on_intel do
      sha256 "97decf3b86120a46eaa20ed9d61fa01531faa93bc97d1a18cc9c8c5006ae9f74"
      url "https://github.com/SamuAlfageme/kompadre/releases/download/v#{version}/kompadre_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/SamuAlfageme/kompadre/"
    end
    on_arm do
      sha256 "861ebba59015d3e9a65adfb0d990c290b546612cce835426cfb3466e2905b403"
      url "https://github.com/SamuAlfageme/kompadre/releases/download/v#{version}/kompadre_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/SamuAlfageme/kompadre/"
    end
  end

  name "kompadre"
  desc "Compare Kubernetes clusters using kubeconfig files"
  homepage "https://github.com/SamuAlfageme/kompadre"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kompadre"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kompadre"]
    end
  end

  # No zap stanza required

end
